#!/usr/bin/env bash
# A script that displays a message indefinitely and handles SIGTERM

# Catch SIGTERM and print the required message
trap "echo I am invincible!!!" SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done;
